### ISSUE TITLE
[FEATURE] Gyms Page Epic

### ISSUE THREAD

**Issue by LukeShay** [routerating/route-rating#2]
Acceptance criteria:
  - [ ] Display gym
    - [ ] name
    - [ ] address
    - [ ] picture
    - [ ] website
  - [ ] Be able to paginate through the gyms
  - [ ] Be able to search gyms by name
  - [ ] Display types of routes for each gym
  - [ ] Display grade range
  - [ ] Filter by location
